return {
    ACTIONFAIL = {
        SHAVE = {
            GENERIC = "Shaving failed!",
            NOBITS = "Nice fur!",
            AWAKEBEEFALO = "Don't wake the Beefalo!",
        },
    },
    DESCRIBE = {
        GLOMMER = "Yuck!",
        GLOMMERFLOWER = {
            GENERIC = "It's dripping slime.",
            DEAD = "Gray slime.",
        },
        GLOMMERWINGS = "Weird wings.",
        GLOMMERFUEL = "Fuel, almost like grog.",
        BELL = "Silence, please!",
        STATUEGLOMMER = {
            GENERIC = "Petrified.",
            EMPTY = "Just a statue.",
        },
        WEBBERSKULL = "A skull.",
        MOLE = {
            HELD = "It doesn't fit in my pocket!",
            UNDERGROUND = "It's digging underground.",
            ABOVEGROUND = "Weird burrow.",
        },
        MOLEHILL = "A small tunnel system.",
        MOLEHAT = "Looking through another nose!",
        NIGHTSTICK = "A night stick.",
        RABBITHOUSE = {
            GENERIC = "Not a real carrot sign.",
            BURNT = "Burnt.",
        },
        TURF_DECIDUOUS = "Ground to step on.",
        TURF_SANDY = "Sandy ground.",
        TURF_BADLANDS = "Badlands ground.",
        BEARGER = "Terrifying!",
        BEARGERVEST = "A warm vest.",
        ICEPACK = "Well insulated.",
        BEARGER_FUR = "Thick fur.",
        BIGFOOT = "Jurassic!",
        BONESHARD = "Bone shard.",
        BUZZARD = "Ugly bird.",
        CACTUS = {
            GENERIC = "A cactus.",
            PICKED = "Spines are gone.",
        },
        CACTUS_MEAT_COOKED = "Better when cooked.",
        CACTUS_MEAT = "Not safe to eat unprepared.",
        CACTUS_FLOWER = "A pretty flower.",
        COLDFIRE = {
            GENERIC = "A good fire.",
            OUT = "Fire's out.",
            EMBERS = "Embers are fading.",
            LOW = "Needs more fuel.",
            NORMAL = "A normal fire.",
            HIGH = "The fire is roaring!",
        },
        CATCOON = "A curious cat.",
        CATCOONDEN = {
            GENERIC = "A good cat shelter.",
            EMPTY = "Empty.",
        },
        CATCOONHAT = "A fitting hat.",
        COONTAIL = "A long tail would be nice.",
        COOKPOT = {
            COOKING_LONG = "It's been cooking for a while.",
            COOKING_SHORT = "Almost done.",
            DONE = "Ready to eat!",
            EMPTY = "It's missing ingredients.",
            BURNT = "Ruined.",
        },
        EYEBRELLAHAT = "An eye-hat.",
        ARMORDRAGONFLY = "Fiery armor!",
        DRAGON_SCALES = "Insect scales.",
        DRAGONFLYCHEST = "Scales, great!",
        DECIDUOUSTREE = {
            GENERIC = "A fragrant tree.",
            CHOPPED = "Fallen over.",
            BURNING = "The tree is burning!",
            BURNT = "Burnt tree.",
            POISON = "Poisonous tree!",
        },
        ACORN_COOKED = "The poison has been cooked out.",
        BIRCHNUTDRAKE = "Run away!",
        FARMPLOT = {
            GENERIC = "A small farm plot.",
            GROWING = "It's growing.",
            NEEDSFERTILIZER = "Needs fertilizer.",
            BURNT = "Burnt.",
        },
        COLDFIREPIT = {
            GENERIC = "A campfire.",
            OUT = "Fire's out.",
            EMBERS = "The embers are fading.",
            LOW = "Needs more fuel.",
            NORMAL = "A fire.",
            HIGH = "The fire is burning fiercely!",
        },
        FIRESUPPRESSOR = {
            ON = "It's on.",
            OFF = "It's off.",
            LOWFUEL = "Low on fuel.",
        },
        ICEHAT = "A cool hat.",
        LIGHTNINGGOAT = {
            GENERIC = "An electricity-generating goat?",
            CHARGED = "Charged!",
        },
        LIGHTNINGGOATHORN = "A mysterious horn.",
        GOATMILK = "Milky!",
        MEATRACK = {
            GENERIC = "For drying meat.",
            DRYING = "It's drying.",
            DRYINGINRAIN = "The rain is stopping it.",
            DONE = "The jerky is ready.",
            BURNT = "Burnt.",
        },
        MERMHEAD = {
            GENERIC = "Unclear if it's rotten.",
            BURNT = "Just ashes.",
        },
        MERMHOUSE = {
            GENERIC = "Dilapidated.",
            BURNT = "Completely burnt.",
        },
        FLOWERSALAD = "A nutritious salad!",
        ICECREAM = "Delicious ice cream!",
        WATERMELONICLE = "Melon on a stick.",
        TRAILMIX = "All natural!",
        HOTCHILI = "Spicy chili!",
        GUACAMOLE = "Guacamole for celebrating.",
        MOOSE = "A large animal.",
        MOOSEEGG = "A large egg!",
        MOSSLING = "As expected.",
        FEATHERFAN = "To circulate air!",
        GOOSE_FEATHER = "Soft down.",
        STAFF_TORNADO = "An unusual staff.",
        PIGHEAD = {
            GENERIC = "A head on a stick.",
            BURNT = "Charred remains.",
        },
        PIGHOUSE = {
            GENERIC = "A pig house.",
            FULL = "Fully occupied.",
            LIGHTSOUT = "It's dark.",
            BURNT = "Burnt.",
        },
        FERTILIZER = "A bucket of poop.",
        RAINOMETER = {
            GENERIC = "It measures the rain.",
            BURNT = "Burnt out.",
        },
        RAINCOAT = "Waterproof.",
        RAINHAT = "A rain hat.",
        RESEARCHLAB = {
            GENERIC = "A research lab.",
            BURNT = "Burnt.",
        },
        RESEARCHLAB2 = {
            GENERIC = "A research lab.",
            BURNT = "Burnt.",
        },
        RESEARCHLAB3 = {
            GENERIC = "Research lab - gone too far.",
            BURNT = "An omen.",
        },
        RESEARCHLAB4 = {
            GENERIC = "Research lab - strange.",
            BURNT = "No more energy.",
        },
        RESURRECTIONSTATUE = {
            GENERIC = "I'm back!",
            BURNT = "Destroyed.",
        },
        ROCK_ICE = {
            GENERIC = "Massive ice.",
            MELTED = "Melted.",
        },
        ROCK_ICE_MELTED = "Melted.",
        ICE = "Ice.",
        REFLECTIVEVEST = "Cools moderately.",
        HAWAIIANSHIRT = "Not a Hawaiian shirt.",
        TENT = {
            GENERIC = "Not a cozy tent.",
            BURNT = "Burnt.",
        },
        SIESTAHUT = {
            GENERIC = "Questionably cozy.",
            BURNT = "Burnt.",
        },
        TRANSISTOR = "Modern technology.",
        TREASURECHEST = {
            GENERIC = "A treasure chest.",
            BURNT = "Completely burnt.",
        },
        TUMBLEWEED = "Dried up plant matter.",
        GRASS_UMBRELLA = "A simple umbrella.",
        UNIMPLEMENTED = "Work in progress.",
        WALL_HAY = {
            GENERIC = "Unstable hay wall.",
            BURNT = "Burnt.",
        },
        WALL_WOOD = {
            GENERIC = "Wooden wall.",
            BURNT = "Burnt.",
        },
        WARG = "A wild wolf.",
        WATERMELON = "Delicious melon.",
        WATERMELON_COOKED = "Grilled, very good.",
        WATERMELONHAT = "A refreshing hat.",
        WINTEROMETER = {
            GENERIC = "Measures the cold.",
            BURNT = "Burnt out.",
        },
        HOMESIGN = {
            GENERIC = "A useful sign.",
            BURNT = "No longer readable.",
        },
        BEEBOX = {
            READY = "Ready to harvest honey.",
            GENERIC = "Honey has its price.",
            FULLHONEY = "Full of honey.",
            NOHONEY = "No honey.",
            SOMEHONEY = "Not yet ripe.",
            BURNT = "Burnt, poor bees.",
        },
        LIVINGTREE = "A special tree.",
        ICESTAFF = "An ice staff.",
        WORMLIGHT = "Soft light.",
        WORM = {
            PLANT = "Reminds me of old stories.",
            DIRT = "Hands off!",
            WORM = "Spare us!",
        },
        EEL = "An eel.",
        EEL_COOKED = "Cooked, edible.",
        UNAGI = "A type of eel.",
        EYETURRET = "A magical weapon.",
        EYETURRET_ITEM = "Place it first.",
        MINOTAURHORN = "A large horn.",
        MINOTAURCHEST = "Large chest.",
        THULECITE_PIECES = "Pieces to assemble.",
        POND_ALGAE = "Algae without photosynthesis.",
        GREENSTAFF = "Green staff that turns back time.",
        POTTEDFERN = "Potted plant.",
        BOOK_BIRDS = "Book about birds - favorite: Megascops kennicottii.",
        BOOK_TENTACLES = "Book about tentacles - captivating.",
        BOOK_GARDENING = "Book about gardening.",
        BOOK_SLEEP = "Book about sleep.",
        BOOK_BRIMSTONE = "Book about Brimstone - risky.",
        SLURPER = "An example of symbiosis.",
        SLURPER_PELT = "Could be useful.",
        ARMORSLURPER = "Disgusting, magical armor.",
        ORANGEAMULET = "Amulet fades with use.",
        YELLOWSTAFF = "Handy yellow staff.",
        YELLOWGEM = "Yellow gemstone, possibly citrine.",
        ORANGEGEM = "Orange gemstone, garnet-like.",
        TELEBASE = {
            VALID = "Ready for use.",
            GEMS = "Not full yet.",
        },
        GEMSOCKET = {
            VALID = "Strange effect.",
            GEMS = "Holds gemstones.",
        },
        STAFFLIGHT = "A larger staff provides more light.",
        ANCIENT_ALTAR = "Ancient monument.",
        ANCIENT_ALTAR_BROKEN = "Parts are missing.",
        ANCIENT_STATUE = "Mystical statue.",
        LICHEN = "Fungus-bacteria symbiosis.",
        CUTLICHEN = "Doesn't last long.",
        
        CAVE_BANANA = "Cave bananas, all the same.",
        CAVE_BANANA_COOKED = "A little better when cooked.",
        CAVE_BANANA_TREE = "Cave banana tree.",
        ROCKY = "A large rock.",
        BLUEAMULET = "Blue amulet, drains energy.",
        PURPLEAMULET = "Purple amulet, attracts something.",
        TELESTAFF = "Tele-staff, focuses fuel.",
        MONKEY = "Monkeys (Monkey Island).",
        MONKEYBARREL = "Barrel of monkeys.",
        HOUNDSTOOTH = "Tooth made of calcium and sulfur.",
        ARMORSNURTLESHELL = "Spacious turtle armor.",
        BAT = "A bat.",
        BATWING = "Bat wing, edible.",
        BATWING_COOKED = "Cooked, edible.",
        BEDROLL_FURRY = "No sleeping on the ground.",
        BUNNYMAN = "Immature rabbit.",
        FLOWER_CAVE = "Cave flower.",
        FLOWER_CAVE_DOUBLE = "Double cave flower.",
        FLOWER_CAVE_TRIPLE = "Triple cave flower.",
        GUANO = "Metabolic waste.",
        LANTERN = "Refillable light source.",
        LIGHTBULB = "A lightbulb?", 
        MANRABBIT_TAIL = "Rabbit tail for balance.",
        MUSHTREE_TALL  = "Tall mushroom tree.",
        MUSHTREE_MEDIUM = "Medium-sized, red mushroom tree.",
        MUSHTREE_SMALL = "Small mushroom tree.",
        SLURTLE = "Rock-eating snail.",
        SLURTLE_SHELLPIECES = "Shell pieces.",
        SLURTLEHAT = "Protective hat.",
        SLURTLEHOLE = "Snail hole.",
        SLURTLESLIME = "Explosive slime.",
        SNURTLE = "Rare snail.",
        SPIDER_HIDER = "Spider with thick armor.",
        SPIDER_SPITTER = "Spider that spits projectiles.",
        SPIDERHOLE = "Spider's den.",
        STALAGMITE = "Rock formation.",
        STALAGMITE_FULL = "Complete formation.",
        STALAGMITE_LOW = "Low.",
        STALAGMITE_MED = "Medium.",
        STALAGMITE_TALL = "Tall formation.",
        STALAGMITE_TALL_FULL = "Full height.",
        STALAGMITE_TALL_LOW = "Low height.",
        STALAGMITE_TALL_MED = "Medium height.",
        TURF_CARPETFLOOR = "Carpeted floor.",
        TURF_CHECKERFLOOR = "Checkered floor.",
        TURF_DIRT = "Dirt floor.",
        TURF_FOREST = "Forest floor.",
        TURF_GRASS = "Grass floor.",
        TURF_MARSH = "Marsh floor.",
        TURF_ROAD = "Road floor.",
        TURF_ROCKY = "Rocky floor.",
        TURF_SAVANNA = "Dusty floor.",
        TURF_WOODFLOOR = "Wooden floor.",
        TURF_CAVE = "Cave floor.",
        TURF_FUNGUS = "Fungus floor.",
        TURF_SINKHOLE = "Sinkhole floor.",
        TURF_UNDERROCK = "Underground floor.",
        TURF_MUD = "Mud floor.",
        BATBAT = "A living weapon.",
        LUREPLANT = "Invasive plant.",
        LUREPLANTBULB = "Moves the plant.",
        EYEPLANT = "Eye plant.",
        PLANTMEAT = "Plant meat.",
        PLANTMEAT_COOKED = "Better when cooked.",
        CAVE_FERN = "Ornamental cave plant.",
        FOLIAGE = "Leaves, possibly nutritious.",
        FOOTBALLHAT = "Protective clothing.",
        POWCAKE = "A crowning cake.",
        CAVE_ENTRANCE = {
            GENERIC = "Cave entrance.",
            OPEN = "The cave is open.",
        },
        CAVE_EXIT = "Leave the cave.",
        
        BOOMERANG = "A boomerang.",
        SPOILED_FOOD = "Spoiled food.",
        ICEBOX = "Ice box.",
        MAXWELLPHONOGRAPH = "Lifeless phonograph.",
        PIGGUARD = "Pig guard.",
        
        DIVININGROD = {
            GENERIC = "Magical dowsing rod.",
            COLD = "Cold.",
            WARM = "Getting warmer.",
            WARMER = "Warmer still.",
            HOT = "Hot!",
        },
        DIVININGRODSTART = "A useful rod.",
        DRAGONFLY = "Dragonfly.",
        LAVASPIT = {
            HOT = "Hot as grog.",
            COOL = "Cooled down.",
        },
        DRAGONFRUIT = "Dragon fruit.",
        DRAGONFRUIT_COOKED = "Cooked, tasty.",
        DRAGONFRUIT_SEEDS = "Dragon fruit seeds.",
        DRAGONPIE = "Dragon pie.",
        DRUMSTICK = "Chicken leg.",
        DRUMSTICK_COOKED = "Cooked, delicious.",
        DURIAN = "Durian - it stinks.",
        DURIAN_COOKED = "Cooked, still stinks.",
        DURIAN_SEEDS = "Durian seeds, they have a peculiar smell.",
        EARMUFFSHAT = "Protects the ears.",
        EGGPLANT = "Eggplant.",
        EGGPLANT_COOKED = "Cooked, tender.",
        EGGPLANT_SEEDS = "Eggplant seeds.",
        WAFFLES = "Waffles.",
        
        WALL_WOOD_ITEM = "Wooden fence element.",
        WALL_STONE_ITEM = "Portable stone.",
        WALL_RUINS_ITEM = "Ruin piece.",
        WALL_HAY_ITEM = "Hay bale.",
        WALL_STONE = "Stone wall.",
        WALL_RUINS = "Ruins wall.",
        ADVENTURE_PORTAL = "Adventure portal.",
        
        BIRDCAGE = {
            GENERIC = "Birdcage.",
            OCCUPIED = "Bird inside.",
            SLEEPING = "Quiet, the bird is sleeping.",
        },
        MEAT = "Raw meat.",
        SMALLMEAT = "Small piece of meat.",
        COOKEDSMALLMEAT = "Cooked, better.",
        MONSTERMEAT = "Monster meat, not edible.",
        MONSTERLASAGNA = "Monster lasagna, not safe." ,
        COOKEDMEAT = "Cooked, more appetizing.",
        MEATBALLS = "Meatballs.",
        UMBRELLA = "A simple umbrella.",
        PERD = "Turkeys - better stay away.",
        TURKEYDINNER = "Turkey dinner.",
        COOKEDMONSTERMEAT = "Cooked, still poisonous.",
        MAXWELL = "Maxwell, rude.",
        TENTACLE = "A tentacle.",
        TENTACLESPIKE = "Spiky, be careful!",
        TENTACLESPOTS = "Tentacle spots.",
        TENTACLE_PILLAR = "Tentacle pillar.",
        TENTACLE_PILLAR_ARM = "Small tentacle arm.",
        TENTACLE_GARDEN = "Tentacle garden.",
        BEEFALO = {
            GENERIC = "Looks bovine.",
            FOLLOWER = "It's following me.",
            NAKED = "Freezing, naked.",
            SLEEPING = "Sleeping.",
        },
        BABYBEEFALO = "Cute baby.",
        MANDRAKE = {
            GENERIC = "Mandragora officinarum.",
            PICKED = "Picked.",
            DEAD = "Mandrake is dead.",
        },
        COOKEDMANDRAKE = "Cooked Mandrake.",
        MANDRAKESOUP = "Mandrake soup.",
        KRAMPUS = "That fiend, Krampus.",
        KRAMPUS_SACK = "A large sack.",
        PINECONE = {
            GENERIC = "A pinecone.",
            PLANTED = "The cone is maturing.",
        },
        ARMORWOOD = "Log suit.",
        ARMOR_SANITY = "Armor that protects sanity.",
        ASH = {
            GENERIC = "Ash, a residue of fire.",
            REMAINS_GLOMMERFLOWER = "The Glommer flower burned.",
            REMAINS_EYE_BONE = "A charred eyebone.",
            REMAINS_THINGIE = "Once something, now ash.",
        },
        SPEAR = "An old spear.",
        STRAWHAT = "A straw hat.",
        STUFFEDEGGPLANT = "Stuffed eggplant.",
        BEEFALOHAT = "Beefalo hat.",
        TOPHAT = "A top hat, very bourgeois.",
        FLOWERHAT = "A flower hat.",
        BUSHHAT = "A camouflage hat.",
        ROPE = "A hemp rope.",
        LOG = "A log.",
        LIVINGLOG = "A living log.",
        LOCKEDWES = "Wes is trapped.",
        TWIGS = "Small twigs.",
        CARROT = "Carrot.",
        CARROT_COOKED = "Roasted carrot.",
        CARROT_PLANTED = "Carrot planted.",
        CARROT_SEEDS = "Carrot seeds.",
        BERRIES = "Berries.",
        BERRIES_COOKED = "Roasted berries.",
        CUTSTONE = "Cut stone slab.",
        SEEDS = "A few seeds.",
        SEEDS_COOKED = "Roasted seeds.",
        SILK = "Silk, a protein fiber.",
        SPIDERGLAND = "Spider gland, slightly toxic.",
        BOARDS = "Wooden planks.",
        BONESTEW = "Bone stew.",
        MAXWELLTHRONE = "Maxwell's throne.",
        MAXWELLLOCK = "The key is missing.",
        MAXWELLLIGHT = "Magical light.",
        FEM_PUPPET = "A female puppet.",
        MALE_PUPPET = "A male puppet.",
        ROBOT_PUPPET = "A robot puppet.",
        NITRE = "Nitre.",
        GUNPOWDER = "Gunpowder.",
        BIRD_EGG = "Bird egg, unfertilized.",
        BIRD_EGG_COOKED = "Cooked, ideal with toast.",
        ROTTENEGG = "Rotten egg.",
        HAMBAT = "A ham bat, not ideal.",
        TRAP_TEETH = "Trap teeth, poisonous.",
        TRAP_TEETH_MAXWELL = "Maxwell's trap teeth.",
        RABBIT = {
            GENERIC = "Rabbit - I like them.",
            HELD = "Cute?",
        },
        ROCK_LIGHT = {
            GENERIC = "Rock with lava.",
            OUT = "Lava is hidden.",
            LOW = "Lava is cooling down.",
            NORMAL = "Lava is hot.",
        },
        ROCK = "A large stone.",
        PIGKING = "Pig King.",
        RATATOUILLE = "Ratatouille, nutritious.",
        RESURRECTIONSTONE = "A strange stone.",
        ROBIN = {
            GENERIC = "A robin.",
            HELD = "In my hand.",
        },
        ROBIN_WINTER = {
            GENERIC = "Winter robin.",
            HELD = "Delicate.",
        },
        AXE = "An axe.",
        HAMMER = "A hammer.",
        PICKAXE = "A pickaxe.",
        SEWING_KIT = "Sewing kit.",
        SHOVEL = "A shovel.",
        PITCHFORK = "A pitchfork.",
        ROCKS = "A bundle of rocks.",
        FIRESTAFF = "A fire staff.",
        FISH = "A fish.",
        FISHINGROD = "Fishing rod.",
        FISHSTICKS = "Fish sticks.",
        FISHTACOS = "Fish tacos.",
        FISH_COOKED = "Grilled fish.",
        FLINT = "Flint.",
        AMULET = "An amulet.",
        RAZOR = "A razor.",
        POMEGRANATE = "Pomegranate.",
        POMEGRANATE_COOKED = "Cooked, delicious.",
        POMEGRANATE_SEEDS = "Pomegranate seeds.",
        POND = "A small pond.",
        LEIF = "Leif? No idea.",
        LEIF_SPARSE = "No idea.",
        SPIDERQUEEN = "Spider Queen.",
        PIGGYBACK = "Face on its back.",
        BLOWDART_FIRE = "Fire dart.",
        BLOWDART_SLEEP = "Sleep dart.",
        BLOWDART_PIPE = "Blowgun.",
        SPIDERHAT = "Spider hat.",
        EARMUFFHAT = "Earmuffs.",
        WETGOOP = "Doesn't fit!",
        WINTERHAT = "A self-knitted winter hat.",
        NIGHTMAREFUEL = "Ectoplasm.",
        NIGHTLIGHT = "Night light.",
        NIGHTSWORD = "Night sword.",
        ARMORMARBLE = "Marble armor.",
        ARMORGRASS = "Grass armor.",
        BLUEPRINT = "Blueprint.",
        BELL_BLUEPRINT = "Blueprint for a bell.",
        MAXWELLHEAD = "Maxwell's head.",
        WALRUSHAT = "Walrus hat.",
        WALRUS = "A walrus.",
        WALRUS_CAMP = {
            GENERIC = "Camp.",
            EMPTY = "Abandoned.",
        },
        LITTLE_WALRUS = "Little walrus.",
        WALRUS_TUSK = "Tusk.",
        SPIDERDEN = "Spider nest.",
        RABBITHOLE = {
            GENERIC = "Rabbit hole.",
            SPRING = "Hope it fits.",
        },
        FIREFLIES = {
            GENERIC = "Fireflies.",
            HELD = "Glowing in my hand.",
        },
        CORN = "Corn.",
        CORN_COOKED = "Popped corn.",
        CORN_SEEDS = "Corn seeds.",
        CROW = {
            GENERIC = "A crow.",
            HELD = "In my hand.",
        },
        GHOST = "A ghost.",
        CUTGRASS = "A few blades of grass.",
        CUTREEDS = "A few reeds.",
        PEROGIES = "Pierogies.",
        PETALS = "Petals.",
        PETALS_EVIL = "Evil petals.",
        FLOWER = "A wildflower.",
        FLOWER_EVIL = "Evil flower.",
        GOLDENAXE = "Golden axe.",
        GOLDENPICKAXE = "Golden pickaxe.",
        GOLDENPITCHFORK = "Golden pitchfork.",
        GOLDENSHOVEL = "Golden shovel.",
        GOLDNUGGET = "Gold nugget.",
        POOP = "Animal droppings.",
        PUMPKIN = "Pumpkin.",
        PUMPKINCOOKIE = "Pumpkin cookies.",
        PUMPKIN_COOKED = "Cooked, sticky.",
        PUMPKIN_LANTERN = "Pumpkin lantern.",
        PUMPKIN_SEEDS = "Pumpkin seeds.",
        TORCH = "Torch.",
        TRAP = "Trap.",
        BEEFALOWOOL = "Beefalo wool.",
        BUGNET = "Bug net.",
        PANFLUTE = "Pan flute.",
        ONEMANBAND = "One-man band.",
        BIRDTRAP = "Bird trap.",
        GEARS = "Gears.",
        STATUEHARP = "Statue harp.",
        STATUEMAXWELL = "Maxwell's statue.",
        SKELETON = "A skeleton.",
        SKELETON_PLAYER = "Player skeleton.",
        RED_MUSHROOM = {
            GENERIC = "Red mushroom.",
            PICKED = "Picked.",
            INGROUND = "In the ground.",
        },
        GREEN_MUSHROOM = {
            GENERIC = "Green mushroom.",
            PICKED = "Picked.",
            INGROUND = "In the ground.",
        },
        BLUE_MUSHROOM = {
            GENERIC = "Blue mushroom.",
            PICKED = "Picked.",
            INGROUND = "In the ground.",
        },
        RED_CAP = "Red cap, poisonous.",
        GREEN_CAP = "Green cap, edible.",
        BLUE_CAP = "Blue cap, medicinal.",
        RED_CAP_COOKED = "Cooked, red cap.",
        GREEN_CAP_COOKED = "Cooked, green cap.",
        BLUE_CAP_COOKED = "Cooked, blue cap.",
        BEE = {
            GENERIC = "A bee.",
            HELD = "In my hand.",
        },
        KILLERBEE = {
            GENERIC = "Killer bee.",
            HELD = "In my hand.",
        },
        MOSQUITO = {
            GENERIC = "A mosquito.",
            HELD = "In my hand.",
        },
        MOSQUITOSACK = "Mosquito sack.",
        BEEHAT = "Bee hat.",
        BEEHIVE = "Beehive.",
        BEEMINE = "Bee mine.",
        BEEMINE_MAXWELL = "Maxwell's bee mine.",
        HONEY = "Honey.",
        HONEYCOMB = "Honeycomb.",
        HONEYHAM = "Honey ham.",
        HONEYNUGGETS = "Honey nuggets.",
        HORN = "A horn.",
        STINGER = "A stinger.",
        SPIDER = {
            GENERIC = "A spider.",
            SLEEPING = "Sleeping.",
            DEAD = "Dead.",
        },
        SPIDER_WARRIOR = {
            GENERIC = "Spider warrior.",
            SLEEPING = "Sleeping.",
            DEAD = "Dead.",
        },
        BERRYBUSH = {
            GENERIC = "Berry bush.",
            PICKED = "Berries are growing back.",
            BARREN = "Barren - action needed.",
            WITHERED = "Withered.",
        },
        DUG_GRASS = "Dug up grass.",
        DUG_SAPLING = "Dug up sapling.",
        DUG_BERRYBUSH = "Dug up berry bush.",
        DUG_MARSH_BUSH = "Dug up marsh bush.",
        SAPLING = {
            GENERIC = "Small sapling.",
            WITHERED = "Withered.",
            PICKED = "Picked.",
            BURNING = "It's burning!",
        },
        GRASS = {
            GENERIC = "Pile of grass.",
            PICKED = "Growing back.",
            BARREN = "Barren, needs fertilizer.",
            WITHERED = "Wilting.",
            BURNING = "Burning.",
        },
        REEDS = {
            GENERIC = "Reeds.",
            PICKED = "Growing back.",
            BURNING = "Burning.",
        },
        RELIC = {
            GENERIC = "A relic.",
            BROKEN = "Broken stone.",
        },
        RUBBLE = "Rubble.",
        PLANT_NORMAL = {
            GENERIC = "A plant.",
            READY = "Ripe.",
            GROWING = "Growing.",
            WITHERED = "Withered.",
        },
        MOUND = {
            GENERIC = "A mound.",
            DUG = "Dug up.",
        },
        PIGMAN = {
            GENERIC = "Semi-intelligent pig.",
            FOLLOWER = "It's following me.",
            DEAD = "Dead.",
            WEREPIG = "Transformed pig.",
            GUARD = "Guard.",
        },
        SPIDEREGGSACK = "Spider egg sac.",
        TELEPORTATO_RING = "Teleport ring.",
        TELEPORTATO_BOX = "Teleport box.",
        TELEPORTATO_CRANK = "Crank.",
        TELEPORTATO_POTATO = "Strange potato.",
        TELEPORTATO_BASE = {
            GENERIC = "Runestone with special properties.",
            PARTIAL = "Partially finished.",
            LOCKED = "Locked.",
            ACTIVE = "Active.",
        },
        BEARDHAIR = "Beard growth.",
        BUTTERFLY = {
            GENERIC = "A butterfly.",
            HELD = "In my hand.",
        },
        BUTTERFLYWINGS = "Butterfly wings.",
        BUTTERFLYMUFFIN = "Butterfly muffin.",
        BUTTER = "Butter.",
        ACORN = {
            GENERIC = "An acorn.",
            PLANTED = "Acorn planted.",
        },
        EVERGREEN = {
            GENERIC = "A coniferous tree.",
            CHOPPED = "Chopped.",
            BURNING = "Burning.",
            BURNT = "Burnt.",
        },
        EVERGREEN_SPARSE = {
            GENERIC = "Sparse coniferous tree.",
            CHOPPED = "Chopped.",
            BURNING = "Burning.",
            BURNT = "Burnt.",
        },
        FIREPIT = {
            GENERIC = "Fire pit.",
            OUT = "Fire is out.",
            EMBERS = "Embers are fading.",
            LOW = "Needs more fuel.",
            NORMAL = "A fire.",
            HIGH = "The fire is burning brightly!",
        },
        HEATROCK = {
            FROZEN = "Frozen rock.",
            COLD = "Cool.",
            GENERIC = "Normal temperature.",
            WARM = "Slightly warm.",
            HOT = "Hot!",
        },
        CAMPFIRE = {
            GENERIC = "Campfire.",
            OUT = "Fire is out.",
            EMBERS = "Embers are fading.",
            LOW = "Needs more wood.",
            NORMAL = "A fire.",
            HIGH = "The fire is burning fiercely!",
        },
        FEATHERHAT = "Feather hat.",
        FEATHER_CROW = "Crow feather.",
        FEATHER_ROBIN = "Robin feather.",
        FEATHER_ROBIN_WINTER = "Winter feather.",
        TRINKET_1 = "Bottle cleaner, pretty.",
        TRINKET_10 = "Not necessary.",
        TRINKET_11 = "Mischievous scale replica.",
        TRINKET_12 = "Muscular apparatus.",
        TRINKET_2 = "Fake membranophone.",
        TRINKET_3 = "Dear bard.",
        TRINKET_4 = "Little, strange fellow.",
        TRINKET_5 = "Insufficiently cooled.",
        TRINKET_6 = "Tangled bundle of wire.",
        TRINKET_7 = "Hands instead of a device.",
        TRINKET_8 = "Reminds me of a bathtub.",
        TRINKET_9 = "No buttons are missing.",
        SKULLCHEST = "Skull chest.",
        PANDORASCHEST = "Pandora's chest.",
        BEDROLL_STRAW = "Straw bed.",
        CHARCOAL = "Charcoal.",
        MARSH_PLANT = "Marsh plant.",
        MARSH_BUSH = {
            GENERIC = "Bramble bush.",
            PICKED = "Berries are growing back.",
            BURNING = "It's burning!",
        },
        PAPYRUS = "Papyrus.",
        MARSH_TREE = {
            GENERIC = "Marsh tree.",
            CHOPPED = "Chopped.",
            BURNING = "Burning.",
            BURNT = "Burnt.",
        },
        FROG = {
            SLEEPING = "Frog is sleeping.",
            DEAD = "Frog is dead.",
            GENERIC = "A frog.",
        },
        FROGGLEBUNWICH = "Frog sandwich.",
        FROGLEGS = "Frog legs.",
        FROGLEGS_COOKED = "Cooked frog legs.",
        FRUITMEDLEY = "Fruit medley.",
        WORMHOLE = {
            GENERIC = "A wormhole.",
            OPEN = "Wormhole is open.",
        },
        CHESSJUNK1 = "Clockwork junk.",
        CHESSJUNK2 = "Mechanical junk.",
        CHESSJUNK3 = "Clockwork junk.",
        CHESTER = "Chester, mobile chest.",
        CHESTER_EYEBONE = {
            GENERIC = "Chester's eyebone.",
            WAITING = "Waiting.",
        },
        TALLBIRD = "Tall bird.",
        SMALLBIRD = {
            GENERIC = "Small bird.",
            HUNGRY = "Hungry.",
            STARVING = "Starving.",
        },
        TEENBIRD = {
            GENERIC = "Teen bird.",
            HUNGRY = "Hungry.",
            STARVING = "Starving.",
        },
        TALLBIRDEGG = "Tall bird egg.",
        TALLBIRDEGG_COOKED = "Cooked tall bird egg.",
        TALLBIRDEGG_CRACKED = {
            GENERIC = "Cracked egg.",
            HOT = "Hot.",
            COLD = "Cold.",
            SHORT = "Soon ripe.",
            LONG = "Slowly cooking.",
        },
        TALLBIRDNEST = {
            GENERIC = "Tall bird nest.",
            PICKED = "Nest is empty.",
        },
        ANIMAL_TRACK = "Animal tracks.",
        DIRTPILE = "Dirt pile.",
        KOALEFANT_SUMMER = "Koalefanta (Summer).",
        KOALEFANT_WINTER = "Koalefanta (Winter).",
        TRUNK_SUMMER = "Practical trunk.",
        TRUNK_WINTER = "Winter trunk.",
        TRUNK_COOKED = "Cooked, not tasty.",
        TRUNKVEST_SUMMER = "Summer vest.",
        TRUNKVEST_WINTER = "Winter vest.",
        DEADLYFEAST = "Deadly feast.",
        DEERCLOPS = "Deerclops.",
        REDGEM = "Red gem.",
        BLUEGEM = "Blue gem.",
        PURPLEGEM = "Purple gem.",
        HOUND = "Wild dog.",
        FIREHOUND = "Fire dog.",
        ICEHOUND = "Ice dog.",
        HOUNDBONE = "Wolf bone.",
        PENGUIN = "Penguin.",
        DEERCLOPS_EYEBALL = "Deerclops eye.",
        DEPLETED_GRASS = {
            GENERIC = "Bundle of grass.",
        },
        BASALT = "Basalt.",
        HOUNDMOUND = "Hound mound.",
        MERM = "Piscean twine.",
        MINERHAT = "Miner hat.",
        KNIGHT = "Automated horse.",
        BISHOP = "Clockwork bishop.",
        ROOK = "Clockwork rook.",
        JAMMYPRESERVES = "Jammypreserves.",
        KABOBS = "Kabobs.",
        INSANITYROCK = {
            INACTIVE = "Insanity rock (inactive).",
            ACTIVE = "Insanity rock (active).",
        },
        SANITYROCK = {
            INACTIVE = "Sanity rock (inactive).",
            ACTIVE = "Sanity rock (active).",
        },
        ANNOUNCE_EAT = {
            GENERIC = "Mmm!",
            SPOILED = "Yuck!",
            STALE = "Not fresh.",
            PAINFUL = "I'm sick.",
            INVALID = "Can't eat that!",
            YUCKY = "I prefer carrots!",
        },
        ANNOUNCE_CANFIX = "\nCan be repaired.",
        ANNOUNCE_ADVENTUREFAIL = "Learn from your mistakes.",
        ANNOUNCE_COLD = "I'm cold.",
        ANNOUNCE_HOT = "I'm hot.",
        ANNOUNCE_HUNGRY = "I'm hungry.",
        ANNOUNCE_TORCH_OUT = "Need torch.",
        ANNOUNCE_DUSK = "It's getting dark.",
        ANNOUNCE_CHARLIE_ATTACK = "Ouch!",
        ANNOUNCE_CHARLIE = "Did you hear that?",
        ANNOUNCE_BOOMERANG = "Boomerang didn't come back.",
        ANNOUNCE_HOUNDS = "Hounds are coming!",
        ANNOUNCE_NOSLEEPONFIRE = "Can't sleep with fire nearby!",
        ANNOUNCE_NODANGERSIESTA = "Can't rest while in danger.",
        ANNOUNCE_NONIGHTSIESTA = "Can't sleep right now.",
        ANNOUNCE_NONIGHTSIESTA_CAVE = "No sleeping in the cave.",
        ANNOUNCE_NOHUNGERSIESTA = "Too hungry to sleep.",
        ANNOUNCE_SHELTER = "Found shelter.",
        ANNOUNCE_BURNT = "Slightly burned.",
        ANNOUNCE_TOOL_SLIP = "Lost my grip!",
        ANNOUNCE_DAMP = "Getting a bit wet.",
        ANNOUNCE_WET = "I'm wet.",
        ANNOUNCE_WETTER = "It's raining.",
        ANNOUNCE_SOAKED = "Completely soaked.",
        ANNOUNCE_PECKED = "Calm down!",
        ANNOUNCE_ENTER_LIGHT = "The light is strong.",
        ANNOUNCE_ENTER_DARK = "Now it's dark.",
        ANNOUNCE_INV_FULL = "Bag is full.",
        ANNOUNCE_CRAFTING_FAIL = "Can't craft that.",
        ANNOUNCE_WORMHOLE = "What the hell?!",
        ANNOUNCE_HUNT_LOST_TRAIL = "Lost the trail.",
        ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Trail washed away by the rain.",
        ANNOUNCE_HUNT_BEAST_NEARBY = "Tracks lead to prey.",
        ANNOUNCE_ACCOMPLISHMENT = "Not done yet!",
        ANNOUNCE_ACCOMPLISHMENT_DONE = "Finished!",
        ANNOUNCE_TRAP_WENT_OFF = "Trap went off!",
        ANNOUNCE_QUAKE = "Quake! At least a 7!",
        ANNOUNCE_NODANGERSLEEP = "Can hardly sleep.",
        ANNOUNCE_INSUFFICIENTFERTILIZER = "Not enough fertilizer.",
        ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Dodged the lightning!",
        ANNOUNCE_TOOMANYBIRDS = "Too many birds.",
        ANNOUNCE_WAYTOOMANYBIRDS = "The sky is empty.",
    },
}
